Controllers/DepartmentsController.cs
using System;
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Matrix.Data;
using Matrix.Data.DomainClasses;
using Matrix.Resources;
using Matrix.Static;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Omu.ValueInjecter;
using Ymas.Extensions;

namespace Matrix.Controllers
{
 
    [Roles("Admin")]
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DepartmentsController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public ActionResult Index(Guid? parentId=null)
        {
            // get all departments recursively 
            var allDep = _db.Departments
                .Where(a => !a.IsDeleted)
                .OrderBy(a => a.ParentId).ThenBy(a => a.NameAr)
                .ToList()
                .SelectRecursive(a=>a.ChildDepartments)
                .Distinct()
                .ToList();
            ViewBag.Title = "";
            if (parentId != null)
            {
                allDep = allDep.Where(a => a.ParentId == parentId).ToList();
            }

            return View(allDep);

        }

        public ActionResult DeletedDepartments()
        {
            var dep = _db.Departments.Where(a => a.IsDeleted).OrderByDescending(a=>a.DeleteDate).ToList();
            return View(dep);
        }
        
        [HttpDelete]
        public ActionResult Restore(Guid? id)
                {
                    if (id == null) return  new StatusCodeResult((int)HttpStatusCode.BadRequest);
                    var item = _db.Departments.Find(id);
                    if(item == null) return new StatusCodeResult((int)HttpStatusCode.NotFound);
                    item.IsDeleted = false;
                    _db.Entry(item).State = EntityState.Modified;
                    var success = _db.SaveChanges();
                     return Json(new{success});
                }
        
        public ActionResult Create()
        {

            PrepareDepartmentLists(null);
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                if (_db.Departments.Any(a => a.NameAr == department.NameAr))
                {
                    TempData["Message"] = department.NameAr+" تم ادخاله سابقا !!";
                    return View(department);            
                }
                department.Id = Guid.NewGuid();
                _db.Departments.Add(department);
                _db.SaveChanges();
                department.NameAr = "";
                department.NameEn = "";
                PrepareDepartmentLists(department);
                TempData["Message"] = _Translate.DataSaevedSuccessfully;
                return View(department);            
            }
            PrepareDepartmentLists(department);
            return View(department);
        }


        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            var dep = _db.Departments.Find(id);
            if(dep == null) return MyHttp.NotFound();
            
            PrepareDepartmentLists(dep);
            return View(dep);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Department depatment)
        {
            if (ModelState.IsValid)
            {
                var dep = _db.Departments.Find(depatment.Id);
                dep.InjectFrom(depatment);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            PrepareDepartmentLists(depatment);
            return View(depatment);
        }

        [HttpDelete]
        public ActionResult Delete(Guid? id)
        {
            if(id == null) return new StatusCodeResult((int)HttpStatusCode.BadRequest);
            var item = _db.Departments.Find(id);
            if(item == null) return new StatusCodeResult((int)HttpStatusCode.NotFound);
            _db.Departments.Remove(item);
            var success = _db.SaveChanges();
            return Json(new{success});
        }
        

        
        
        private void PrepareDepartmentLists(Department department)
        {
            ViewBag.Type = Constants.DepartmentType.SelectList(department?.Type);
            var dep = _db.Departments.Where(a =>
                    a.Type == Constants.DepartmentType.Department || a.Type == Constants.DepartmentType.Division)
                .ToList()
                .Select(a => new 
                {
                    Text = a.NameAr, Value = a.Id.ToString(), Group =  a.ParentDepartment?.NameAr ?? a.NameAr
                }).ToList();
            ViewBag.ParentId = new SelectList(dep, "Value" , "Text" , department?.ParentId,"Group");
        }
        
        protected override void Dispose(bool disposing)
                {
                    if (disposing)
                    {
                        _db.Dispose();
                    }
                    base.Dispose(disposing);
                }

    }
}

Views/Departments/Create.cshtml
@model Matrix.Data.DomainClasses.Department

@{
    ViewBag.Title = _Translate.Add_New;
}


<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-right ">
            @ViewBag.Title        
        </h4>
        <div class="btn-group pull-left">
            <a class="btn btn-sm btn-primary navbar-btn pull-left" href="@Url.Action("Create")" title="@_Translate.CreateNew"><i class="fa fa-plus-circle"></i> @_Translate.CreateNew</a>
        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Create", "Departments", FormMethod.Post, new { enctype = "multipart/form-data" })) 
        {
            @Html.AntiForgeryToken()
        
            <div class="form-horizontal">
            
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                
                
                <div class="form-group">
                    @Html.LabelFor(model => model.ParentId, null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control select " })
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                            @Html.LabelFor(model => model.Type, null, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control select " })
                                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                            </div>
                </div>
                        
     
                
                <div class="form-group"> 
                    @Html.LabelFor(a=>a.NameAr, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control", placeholder = "NameAr in arabic" } })
                        @Html.ValidationMessageFor(model => model.NameAr, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group"> 
                    @Html.LabelFor(a=>a.NameEn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control", placeholder = "NameAr in english" , style="text-align: left !importent" } })
                        @Html.ValidationMessageFor(model => model.NameEn, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.GrpId, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.GrpId, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.GrpId, "", new { @class = "text-danger" })
                                    </div>
                 </div>
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.SupervisorName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupervisorName, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.SupervisorName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.SupervisorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupervisorEmail, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.SupervisorEmail, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="@_Translate.Submit" class="btn btn-primary btn-block btn-lg" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Departments/DeletedDepartments.cshtml
@using Ymas.Extensions
@model IEnumerable<Matrix.Data.DomainClasses.Department>  

@{
    ViewBag.Title = "Deleted Departments";
    
}


<link href="~/Content/jsTree/themes/default/style.min.css" rel="stylesheet" />  


<div class="panel panel-default">
    <div class="panel-heading">Departments</div>
    <div class="panel-body">
         <table class="table table-bordered table-striped">
                     <thead>
                     <tr>
                         <th>#</th>
                         <th>@Html.DisplayNameFor(model=>model.NameAr)</th>
                         <th>@Html.DisplayNameFor(model=>model.NameEn)</th>
                         <th>Sub Departments</th>
                         <th>Deleted By</th>
                         <th>Deleted time</th>
                         <th>Actions</th>
                     </tr>
                     </thead>
             <tbody>
             @foreach (var item in Model)
             {
                 var NameAr = string.Empty;
                 switch (item.Type)
                 {
                     case Constants.DepartmentType.Division :
                         NameAr = " >> " + item.NameAr;
                         break;
                         case Constants.DepartmentType.Unit:
                             NameAr = "   >>>   " + item.NameAr;
                             break;
                         default :
                             NameAr = " > "+item.NameAr;
                             break;
                 }
                                 
                 <tr>
                     <td><a href="@Url.Action("Index", new {parentId = item.Id})"><span class="fa fa-info"></span></a></td>
                     <td>@NameAr</td>
                     <td>@item.NameEn</td>
                     <td>@item.ChildDepartments.Count()</td>
                     <td>@item.DeleteByName</td>
                     <td>@item.DeleteDate.ToDatePicker()</td>
                     <td>
                         <div class="actions">
                             <button class="btn btn-sm btn-danger delete" data-Cancel="Cancel" data-SweetAlertconfirmButtonText="Yes, I'am" data-SweetAlertText="Are you to sure ?" data-SweetAlertTitle="Restore Deleted Department!" data-url="@Url.Action("Restore", new {id = item.Id})" title="Restore"><i class="fa  fa-refresh"></i></button>
                         </div>
                     </td>
                     
                 </tr>
             }
             </tbody>
                 </table>
    </div>
</div>

Views/Departments/Edit.cshtml
@model Matrix.Data.DomainClasses.Department

@{
    ViewBag.Title = _Translate.Edit;
}


<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-right ">
            @ViewBag.Title        
        </h4>
        <div class="btn-group pull-left">
            <a class="btn btn-sm btn-primary navbar-btn pull-left" href="@Url.Action("Create")" title="@_Translate.CreateNew"><i class="fa fa-plus-circle"></i> @_Translate.CreateNew</a>
        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "Departments", FormMethod.Post, new { enctype = "multipart/form-data" })) 
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model=>model.Id)
            <div class="form-horizontal">
            
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                
                @{
                    var s = Model.ParentId == null ? "select-empty" : "select";
                }
                <div class="form-group">
                    @Html.LabelFor(model => model.ParentId, null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control  " +s})
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                            @Html.LabelFor(model => model.Type, null, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control select " })
                                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                            </div>
                </div>
                        
     
                
                <div class="form-group"> 
                    @Html.LabelFor(a=>a.NameAr, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control", placeholder = "NameAr in arabic" } })
                        @Html.ValidationMessageFor(model => model.NameAr, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group"> 
                    @Html.LabelFor(a=>a.NameEn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control", placeholder = "NameAr in english" , style="text-align: left !importent" } })
                        @Html.ValidationMessageFor(model => model.NameEn, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.GrpId, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.GrpId, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.GrpId, "", new { @class = "text-danger" })
                                    </div>
                 </div>
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.SupervisorName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupervisorName, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.SupervisorName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                
                
                <div class="form-group"> 
                                    @Html.LabelFor(a=>a.SupervisorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupervisorEmail, new { htmlAttributes = new { @class = "form-control", placeholder = "" } })
                                        @Html.ValidationMessageFor(model => model.SupervisorEmail, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="@_Translate.Submit" class="btn btn-primary btn-block btn-lg" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Departments/Index.cshtml
@model IEnumerable<Matrix.Data.DomainClasses.Department>  

@{
    ViewBag.Title = _Translate.Hierarchy;
    
    
}
<style>
    .dd-handle {
        height: 33px !important;
        }

</style>
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-right ">
            @ViewBag.Title        
        </h4>
        
    </div>    <div class="panel-body">


        <div class="dd" id="nestable">
            <ol class="dd-list">
                @foreach (var item in Model.Where(a => a.ParentId == null))
                {
                    <li class="dd-item" data-id="@item.Id">
                        <div class="dd-handle">@item.TrName
                            <button class="btn btn-xs btn-info pull-left m-lr-5" title="Edit" data-url="@Url.Action("Edit", new {id = item.Id})"><i class="fa  fa-edit"></i></button>
                            <button class="btn btn-xs btn-danger delete pull-left" data-url="@Url.Action("Delete", new {id = item.Id})" title="Delete"><i class="fa  fa-remove"></i></button>
                        </div>
                        @if (item.ChildDepartments.Any())
                        {
                            <ol class="dd-list">
                                @foreach (var dev in item.ChildDepartments)
                                {
                                    <li class="dd-item" data-id="@dev.Id">
                                        <div class="dd-handle">@dev.TrName
                                            <button class="btn btn-xs btn-info pull-left m-lr-5" title="Edit" data-url="@Url.Action("Edit", new {id = dev.Id})"><i class="fa  fa-edit"></i></button>
                                            <button class="btn btn-xs btn-danger delete pull-left" data-url="@Url.Action("Delete", new {id = dev.Id})" title="Delete"><i class="fa  fa-remove"></i></button>
                                        </div>
                                        @if (dev.ChildDepartments.Any())
                                        {
                                            <ol class="dd-list">
                                                @foreach (var un in dev.ChildDepartments)
                                                {
                                                    <li class="dd-item" data-id="@un.Id">
                                                        <div class="dd-handle">@un.TrName
                                                            <button class="btn btn-xs btn-info pull-left m-lr-5" title="Edit" data-url="@Url.Action("Edit", new {id = un.Id})"><i class="fa  fa-edit"></i></button>
                                                            <button class="btn btn-xs btn-danger delete pull-left" data-url="@Url.Action("Delete", new {id = un.Id})" title="Delete"><i class="fa  fa-remove"></i></button>
                                                            </div>
                                                    </li>
                                                }

                                            </ol>
                                        }
                                    </li>
                                }

                            </ol>
                        }
                    </li>
                }


            </ol>
        </div><!-- dd -->
        
    </div>
</div>

@section scripts{
    <script src="~/js/jquery.nestable.min.js"></script>
    <script>
        $(function()	{
            $('.dd').nestable();
        });
    </script>
}